# Generated by Django 5.0.2 on 2024-02-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Nume', models.CharField(max_length=255)),
                ('Prenume', models.CharField(max_length=255)),
                ('CNP', models.CharField(max_length=13, unique=True)),
                ('Parafa', models.CharField(max_length=255, unique=True)),
                ('numar_de_telefon', models.CharField(max_length=10)),
                ('specializare', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
