# Generated by Django 5.0.2 on 2024-02-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_medic'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='email',
            field=models.EmailField(default='<EMAIL>', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='pacient',
            name='email',
            field=models.EmailField(default='<EMAIL>', max_length=254, unique=True),
        ),
    ]
