# Generated by Django 5.0.2 on 2024-02-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_medic_email_pacient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
