# Generated by Django 5.0.2 on 2024-02-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_programare'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='oras',
            field=models.CharField(default='oras', max_length=255),
        ),
    ]
