# Generated by Django 5.0.2 on 2024-02-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_medic_oras'),
    ]

    operations = [
        migrations.AddField(
            model_name='programare',
            name='parafa_medic',
            field=models.CharField(default='parafa_medic', max_length=255),
        ),
    ]
