# Generated by Django 5.0.2 on 2024-03-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_programare_parafa_medic'),
    ]

    operations = [
        migrations.AddField(
            model_name='programare',
            name='aprobat',
            field=models.BooleanField(default=False),
        ),
    ]
