# Generated by Django 5.0.2 on 2024-03-10 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_programare_aprobat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomandare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.medic')),
                ('programare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.programare')),
            ],
        ),
    ]
