# Generated by Django 5.0.2 on 2024-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_recomandare'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='oras',
            field=models.CharField(default='oras', max_length=255),
        ),
    ]
